// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class MoodEntries extends Table with TableInfo<MoodEntries, MoodEntriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MoodEntries(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> occurredAt = GeneratedColumn<int>(
    'occurred_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> mood = GeneratedColumn<int>(
    'mood',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> note = GeneratedColumn<String>(
    'note',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  @override
  List<GeneratedColumn> get $columns => [id, occurredAt, mood, note, createdAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'mood_entries';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  MoodEntriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return MoodEntriesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      occurredAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}occurred_at'],
      )!,
      mood: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}mood'],
      )!,
      note: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}note'],
      ),
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  MoodEntries createAlias(String alias) {
    return MoodEntries(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class MoodEntriesData extends DataClass implements Insertable<MoodEntriesData> {
  final String id;
  final int occurredAt;
  final int mood;
  final String? note;
  final int createdAt;
  const MoodEntriesData({
    required this.id,
    required this.occurredAt,
    required this.mood,
    this.note,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['occurred_at'] = Variable<int>(occurredAt);
    map['mood'] = Variable<int>(mood);
    if (!nullToAbsent || note != null) {
      map['note'] = Variable<String>(note);
    }
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  MoodEntriesCompanion toCompanion(bool nullToAbsent) {
    return MoodEntriesCompanion(
      id: Value(id),
      occurredAt: Value(occurredAt),
      mood: Value(mood),
      note: note == null && nullToAbsent ? const Value.absent() : Value(note),
      createdAt: Value(createdAt),
    );
  }

  factory MoodEntriesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return MoodEntriesData(
      id: serializer.fromJson<String>(json['id']),
      occurredAt: serializer.fromJson<int>(json['occurredAt']),
      mood: serializer.fromJson<int>(json['mood']),
      note: serializer.fromJson<String?>(json['note']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'occurredAt': serializer.toJson<int>(occurredAt),
      'mood': serializer.toJson<int>(mood),
      'note': serializer.toJson<String?>(note),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  MoodEntriesData copyWith({
    String? id,
    int? occurredAt,
    int? mood,
    Value<String?> note = const Value.absent(),
    int? createdAt,
  }) => MoodEntriesData(
    id: id ?? this.id,
    occurredAt: occurredAt ?? this.occurredAt,
    mood: mood ?? this.mood,
    note: note.present ? note.value : this.note,
    createdAt: createdAt ?? this.createdAt,
  );
  MoodEntriesData copyWithCompanion(MoodEntriesCompanion data) {
    return MoodEntriesData(
      id: data.id.present ? data.id.value : this.id,
      occurredAt: data.occurredAt.present
          ? data.occurredAt.value
          : this.occurredAt,
      mood: data.mood.present ? data.mood.value : this.mood,
      note: data.note.present ? data.note.value : this.note,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('MoodEntriesData(')
          ..write('id: $id, ')
          ..write('occurredAt: $occurredAt, ')
          ..write('mood: $mood, ')
          ..write('note: $note, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, occurredAt, mood, note, createdAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is MoodEntriesData &&
          other.id == this.id &&
          other.occurredAt == this.occurredAt &&
          other.mood == this.mood &&
          other.note == this.note &&
          other.createdAt == this.createdAt);
}

class MoodEntriesCompanion extends UpdateCompanion<MoodEntriesData> {
  final Value<String> id;
  final Value<int> occurredAt;
  final Value<int> mood;
  final Value<String?> note;
  final Value<int> createdAt;
  final Value<int> rowid;
  const MoodEntriesCompanion({
    this.id = const Value.absent(),
    this.occurredAt = const Value.absent(),
    this.mood = const Value.absent(),
    this.note = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  MoodEntriesCompanion.insert({
    required String id,
    required int occurredAt,
    required int mood,
    this.note = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       occurredAt = Value(occurredAt),
       mood = Value(mood);
  static Insertable<MoodEntriesData> custom({
    Expression<String>? id,
    Expression<int>? occurredAt,
    Expression<int>? mood,
    Expression<String>? note,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (occurredAt != null) 'occurred_at': occurredAt,
      if (mood != null) 'mood': mood,
      if (note != null) 'note': note,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  MoodEntriesCompanion copyWith({
    Value<String>? id,
    Value<int>? occurredAt,
    Value<int>? mood,
    Value<String?>? note,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return MoodEntriesCompanion(
      id: id ?? this.id,
      occurredAt: occurredAt ?? this.occurredAt,
      mood: mood ?? this.mood,
      note: note ?? this.note,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (occurredAt.present) {
      map['occurred_at'] = Variable<int>(occurredAt.value);
    }
    if (mood.present) {
      map['mood'] = Variable<int>(mood.value);
    }
    if (note.present) {
      map['note'] = Variable<String>(note.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('MoodEntriesCompanion(')
          ..write('id: $id, ')
          ..write('occurredAt: $occurredAt, ')
          ..write('mood: $mood, ')
          ..write('note: $note, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class MoodEntryEmotions extends Table
    with TableInfo<MoodEntryEmotions, MoodEntryEmotionsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MoodEntryEmotions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> moodEntryId = GeneratedColumn<String>(
    'mood_entry_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES mood_entries(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> emotionKey = GeneratedColumn<String>(
    'emotion_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> intensity = GeneratedColumn<int>(
    'intensity',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [moodEntryId, emotionKey, intensity];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'mood_entry_emotions';
  @override
  Set<GeneratedColumn> get $primaryKey => {moodEntryId, emotionKey};
  @override
  MoodEntryEmotionsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return MoodEntryEmotionsData(
      moodEntryId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}mood_entry_id'],
      )!,
      emotionKey: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}emotion_key'],
      )!,
      intensity: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}intensity'],
      )!,
    );
  }

  @override
  MoodEntryEmotions createAlias(String alias) {
    return MoodEntryEmotions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(mood_entry_id, emotion_key)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class MoodEntryEmotionsData extends DataClass
    implements Insertable<MoodEntryEmotionsData> {
  final String moodEntryId;
  final String emotionKey;
  final int intensity;
  const MoodEntryEmotionsData({
    required this.moodEntryId,
    required this.emotionKey,
    required this.intensity,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['mood_entry_id'] = Variable<String>(moodEntryId);
    map['emotion_key'] = Variable<String>(emotionKey);
    map['intensity'] = Variable<int>(intensity);
    return map;
  }

  MoodEntryEmotionsCompanion toCompanion(bool nullToAbsent) {
    return MoodEntryEmotionsCompanion(
      moodEntryId: Value(moodEntryId),
      emotionKey: Value(emotionKey),
      intensity: Value(intensity),
    );
  }

  factory MoodEntryEmotionsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return MoodEntryEmotionsData(
      moodEntryId: serializer.fromJson<String>(json['moodEntryId']),
      emotionKey: serializer.fromJson<String>(json['emotionKey']),
      intensity: serializer.fromJson<int>(json['intensity']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'moodEntryId': serializer.toJson<String>(moodEntryId),
      'emotionKey': serializer.toJson<String>(emotionKey),
      'intensity': serializer.toJson<int>(intensity),
    };
  }

  MoodEntryEmotionsData copyWith({
    String? moodEntryId,
    String? emotionKey,
    int? intensity,
  }) => MoodEntryEmotionsData(
    moodEntryId: moodEntryId ?? this.moodEntryId,
    emotionKey: emotionKey ?? this.emotionKey,
    intensity: intensity ?? this.intensity,
  );
  MoodEntryEmotionsData copyWithCompanion(MoodEntryEmotionsCompanion data) {
    return MoodEntryEmotionsData(
      moodEntryId: data.moodEntryId.present
          ? data.moodEntryId.value
          : this.moodEntryId,
      emotionKey: data.emotionKey.present
          ? data.emotionKey.value
          : this.emotionKey,
      intensity: data.intensity.present ? data.intensity.value : this.intensity,
    );
  }

  @override
  String toString() {
    return (StringBuffer('MoodEntryEmotionsData(')
          ..write('moodEntryId: $moodEntryId, ')
          ..write('emotionKey: $emotionKey, ')
          ..write('intensity: $intensity')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(moodEntryId, emotionKey, intensity);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is MoodEntryEmotionsData &&
          other.moodEntryId == this.moodEntryId &&
          other.emotionKey == this.emotionKey &&
          other.intensity == this.intensity);
}

class MoodEntryEmotionsCompanion
    extends UpdateCompanion<MoodEntryEmotionsData> {
  final Value<String> moodEntryId;
  final Value<String> emotionKey;
  final Value<int> intensity;
  final Value<int> rowid;
  const MoodEntryEmotionsCompanion({
    this.moodEntryId = const Value.absent(),
    this.emotionKey = const Value.absent(),
    this.intensity = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  MoodEntryEmotionsCompanion.insert({
    required String moodEntryId,
    required String emotionKey,
    required int intensity,
    this.rowid = const Value.absent(),
  }) : moodEntryId = Value(moodEntryId),
       emotionKey = Value(emotionKey),
       intensity = Value(intensity);
  static Insertable<MoodEntryEmotionsData> custom({
    Expression<String>? moodEntryId,
    Expression<String>? emotionKey,
    Expression<int>? intensity,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (moodEntryId != null) 'mood_entry_id': moodEntryId,
      if (emotionKey != null) 'emotion_key': emotionKey,
      if (intensity != null) 'intensity': intensity,
      if (rowid != null) 'rowid': rowid,
    });
  }

  MoodEntryEmotionsCompanion copyWith({
    Value<String>? moodEntryId,
    Value<String>? emotionKey,
    Value<int>? intensity,
    Value<int>? rowid,
  }) {
    return MoodEntryEmotionsCompanion(
      moodEntryId: moodEntryId ?? this.moodEntryId,
      emotionKey: emotionKey ?? this.emotionKey,
      intensity: intensity ?? this.intensity,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (moodEntryId.present) {
      map['mood_entry_id'] = Variable<String>(moodEntryId.value);
    }
    if (emotionKey.present) {
      map['emotion_key'] = Variable<String>(emotionKey.value);
    }
    if (intensity.present) {
      map['intensity'] = Variable<int>(intensity.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('MoodEntryEmotionsCompanion(')
          ..write('moodEntryId: $moodEntryId, ')
          ..write('emotionKey: $emotionKey, ')
          ..write('intensity: $intensity, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class JournalEntries extends Table
    with TableInfo<JournalEntries, JournalEntriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  JournalEntries(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> entryDate = GeneratedColumn<int>(
    'entry_date',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> bodyMarkdown = GeneratedColumn<String>(
    'body_markdown',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    entryDate,
    createdAt,
    updatedAt,
    title,
    bodyMarkdown,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'journal_entries';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  JournalEntriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return JournalEntriesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      entryDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}entry_date'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      updatedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      ),
      bodyMarkdown: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}body_markdown'],
      )!,
    );
  }

  @override
  JournalEntries createAlias(String alias) {
    return JournalEntries(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class JournalEntriesData extends DataClass
    implements Insertable<JournalEntriesData> {
  final String id;
  final int entryDate;
  final int createdAt;
  final int updatedAt;
  final String? title;
  final String bodyMarkdown;
  const JournalEntriesData({
    required this.id,
    required this.entryDate,
    required this.createdAt,
    required this.updatedAt,
    this.title,
    required this.bodyMarkdown,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['entry_date'] = Variable<int>(entryDate);
    map['created_at'] = Variable<int>(createdAt);
    map['updated_at'] = Variable<int>(updatedAt);
    if (!nullToAbsent || title != null) {
      map['title'] = Variable<String>(title);
    }
    map['body_markdown'] = Variable<String>(bodyMarkdown);
    return map;
  }

  JournalEntriesCompanion toCompanion(bool nullToAbsent) {
    return JournalEntriesCompanion(
      id: Value(id),
      entryDate: Value(entryDate),
      createdAt: Value(createdAt),
      updatedAt: Value(updatedAt),
      title: title == null && nullToAbsent
          ? const Value.absent()
          : Value(title),
      bodyMarkdown: Value(bodyMarkdown),
    );
  }

  factory JournalEntriesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return JournalEntriesData(
      id: serializer.fromJson<String>(json['id']),
      entryDate: serializer.fromJson<int>(json['entryDate']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      updatedAt: serializer.fromJson<int>(json['updatedAt']),
      title: serializer.fromJson<String?>(json['title']),
      bodyMarkdown: serializer.fromJson<String>(json['bodyMarkdown']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'entryDate': serializer.toJson<int>(entryDate),
      'createdAt': serializer.toJson<int>(createdAt),
      'updatedAt': serializer.toJson<int>(updatedAt),
      'title': serializer.toJson<String?>(title),
      'bodyMarkdown': serializer.toJson<String>(bodyMarkdown),
    };
  }

  JournalEntriesData copyWith({
    String? id,
    int? entryDate,
    int? createdAt,
    int? updatedAt,
    Value<String?> title = const Value.absent(),
    String? bodyMarkdown,
  }) => JournalEntriesData(
    id: id ?? this.id,
    entryDate: entryDate ?? this.entryDate,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    title: title.present ? title.value : this.title,
    bodyMarkdown: bodyMarkdown ?? this.bodyMarkdown,
  );
  JournalEntriesData copyWithCompanion(JournalEntriesCompanion data) {
    return JournalEntriesData(
      id: data.id.present ? data.id.value : this.id,
      entryDate: data.entryDate.present ? data.entryDate.value : this.entryDate,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      updatedAt: data.updatedAt.present ? data.updatedAt.value : this.updatedAt,
      title: data.title.present ? data.title.value : this.title,
      bodyMarkdown: data.bodyMarkdown.present
          ? data.bodyMarkdown.value
          : this.bodyMarkdown,
    );
  }

  @override
  String toString() {
    return (StringBuffer('JournalEntriesData(')
          ..write('id: $id, ')
          ..write('entryDate: $entryDate, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('title: $title, ')
          ..write('bodyMarkdown: $bodyMarkdown')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, entryDate, createdAt, updatedAt, title, bodyMarkdown);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is JournalEntriesData &&
          other.id == this.id &&
          other.entryDate == this.entryDate &&
          other.createdAt == this.createdAt &&
          other.updatedAt == this.updatedAt &&
          other.title == this.title &&
          other.bodyMarkdown == this.bodyMarkdown);
}

class JournalEntriesCompanion extends UpdateCompanion<JournalEntriesData> {
  final Value<String> id;
  final Value<int> entryDate;
  final Value<int> createdAt;
  final Value<int> updatedAt;
  final Value<String?> title;
  final Value<String> bodyMarkdown;
  final Value<int> rowid;
  const JournalEntriesCompanion({
    this.id = const Value.absent(),
    this.entryDate = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.title = const Value.absent(),
    this.bodyMarkdown = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  JournalEntriesCompanion.insert({
    required String id,
    required int entryDate,
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.title = const Value.absent(),
    required String bodyMarkdown,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       entryDate = Value(entryDate),
       bodyMarkdown = Value(bodyMarkdown);
  static Insertable<JournalEntriesData> custom({
    Expression<String>? id,
    Expression<int>? entryDate,
    Expression<int>? createdAt,
    Expression<int>? updatedAt,
    Expression<String>? title,
    Expression<String>? bodyMarkdown,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (entryDate != null) 'entry_date': entryDate,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (title != null) 'title': title,
      if (bodyMarkdown != null) 'body_markdown': bodyMarkdown,
      if (rowid != null) 'rowid': rowid,
    });
  }

  JournalEntriesCompanion copyWith({
    Value<String>? id,
    Value<int>? entryDate,
    Value<int>? createdAt,
    Value<int>? updatedAt,
    Value<String?>? title,
    Value<String>? bodyMarkdown,
    Value<int>? rowid,
  }) {
    return JournalEntriesCompanion(
      id: id ?? this.id,
      entryDate: entryDate ?? this.entryDate,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      title: title ?? this.title,
      bodyMarkdown: bodyMarkdown ?? this.bodyMarkdown,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (entryDate.present) {
      map['entry_date'] = Variable<int>(entryDate.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (updatedAt.present) {
      map['updated_at'] = Variable<int>(updatedAt.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (bodyMarkdown.present) {
      map['body_markdown'] = Variable<String>(bodyMarkdown.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('JournalEntriesCompanion(')
          ..write('id: $id, ')
          ..write('entryDate: $entryDate, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('title: $title, ')
          ..write('bodyMarkdown: $bodyMarkdown, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class Tasks extends Table with TableInfo<Tasks, TasksData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Tasks(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> descriptionMarkdown =
      GeneratedColumn<String>(
        'description_markdown',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> dueDate = GeneratedColumn<int>(
    'due_date',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> status = GeneratedColumn<int>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> completedAt = GeneratedColumn<int>(
    'completed_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> closingNote = GeneratedColumn<String>(
    'closing_note',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    createdAt,
    title,
    descriptionMarkdown,
    dueDate,
    status,
    completedAt,
    closingNote,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'tasks';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TasksData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TasksData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      )!,
      descriptionMarkdown: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}description_markdown'],
      ),
      dueDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}due_date'],
      ),
      status: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}status'],
      )!,
      completedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}completed_at'],
      ),
      closingNote: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}closing_note'],
      ),
    );
  }

  @override
  Tasks createAlias(String alias) {
    return Tasks(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TasksData extends DataClass implements Insertable<TasksData> {
  final String id;
  final int createdAt;
  final String title;
  final String? descriptionMarkdown;
  final int? dueDate;
  final int status;
  final int? completedAt;
  final String? closingNote;
  const TasksData({
    required this.id,
    required this.createdAt,
    required this.title,
    this.descriptionMarkdown,
    this.dueDate,
    required this.status,
    this.completedAt,
    this.closingNote,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['created_at'] = Variable<int>(createdAt);
    map['title'] = Variable<String>(title);
    if (!nullToAbsent || descriptionMarkdown != null) {
      map['description_markdown'] = Variable<String>(descriptionMarkdown);
    }
    if (!nullToAbsent || dueDate != null) {
      map['due_date'] = Variable<int>(dueDate);
    }
    map['status'] = Variable<int>(status);
    if (!nullToAbsent || completedAt != null) {
      map['completed_at'] = Variable<int>(completedAt);
    }
    if (!nullToAbsent || closingNote != null) {
      map['closing_note'] = Variable<String>(closingNote);
    }
    return map;
  }

  TasksCompanion toCompanion(bool nullToAbsent) {
    return TasksCompanion(
      id: Value(id),
      createdAt: Value(createdAt),
      title: Value(title),
      descriptionMarkdown: descriptionMarkdown == null && nullToAbsent
          ? const Value.absent()
          : Value(descriptionMarkdown),
      dueDate: dueDate == null && nullToAbsent
          ? const Value.absent()
          : Value(dueDate),
      status: Value(status),
      completedAt: completedAt == null && nullToAbsent
          ? const Value.absent()
          : Value(completedAt),
      closingNote: closingNote == null && nullToAbsent
          ? const Value.absent()
          : Value(closingNote),
    );
  }

  factory TasksData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TasksData(
      id: serializer.fromJson<String>(json['id']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      title: serializer.fromJson<String>(json['title']),
      descriptionMarkdown: serializer.fromJson<String?>(
        json['descriptionMarkdown'],
      ),
      dueDate: serializer.fromJson<int?>(json['dueDate']),
      status: serializer.fromJson<int>(json['status']),
      completedAt: serializer.fromJson<int?>(json['completedAt']),
      closingNote: serializer.fromJson<String?>(json['closingNote']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'createdAt': serializer.toJson<int>(createdAt),
      'title': serializer.toJson<String>(title),
      'descriptionMarkdown': serializer.toJson<String?>(descriptionMarkdown),
      'dueDate': serializer.toJson<int?>(dueDate),
      'status': serializer.toJson<int>(status),
      'completedAt': serializer.toJson<int?>(completedAt),
      'closingNote': serializer.toJson<String?>(closingNote),
    };
  }

  TasksData copyWith({
    String? id,
    int? createdAt,
    String? title,
    Value<String?> descriptionMarkdown = const Value.absent(),
    Value<int?> dueDate = const Value.absent(),
    int? status,
    Value<int?> completedAt = const Value.absent(),
    Value<String?> closingNote = const Value.absent(),
  }) => TasksData(
    id: id ?? this.id,
    createdAt: createdAt ?? this.createdAt,
    title: title ?? this.title,
    descriptionMarkdown: descriptionMarkdown.present
        ? descriptionMarkdown.value
        : this.descriptionMarkdown,
    dueDate: dueDate.present ? dueDate.value : this.dueDate,
    status: status ?? this.status,
    completedAt: completedAt.present ? completedAt.value : this.completedAt,
    closingNote: closingNote.present ? closingNote.value : this.closingNote,
  );
  TasksData copyWithCompanion(TasksCompanion data) {
    return TasksData(
      id: data.id.present ? data.id.value : this.id,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      title: data.title.present ? data.title.value : this.title,
      descriptionMarkdown: data.descriptionMarkdown.present
          ? data.descriptionMarkdown.value
          : this.descriptionMarkdown,
      dueDate: data.dueDate.present ? data.dueDate.value : this.dueDate,
      status: data.status.present ? data.status.value : this.status,
      completedAt: data.completedAt.present
          ? data.completedAt.value
          : this.completedAt,
      closingNote: data.closingNote.present
          ? data.closingNote.value
          : this.closingNote,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TasksData(')
          ..write('id: $id, ')
          ..write('createdAt: $createdAt, ')
          ..write('title: $title, ')
          ..write('descriptionMarkdown: $descriptionMarkdown, ')
          ..write('dueDate: $dueDate, ')
          ..write('status: $status, ')
          ..write('completedAt: $completedAt, ')
          ..write('closingNote: $closingNote')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    createdAt,
    title,
    descriptionMarkdown,
    dueDate,
    status,
    completedAt,
    closingNote,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TasksData &&
          other.id == this.id &&
          other.createdAt == this.createdAt &&
          other.title == this.title &&
          other.descriptionMarkdown == this.descriptionMarkdown &&
          other.dueDate == this.dueDate &&
          other.status == this.status &&
          other.completedAt == this.completedAt &&
          other.closingNote == this.closingNote);
}

class TasksCompanion extends UpdateCompanion<TasksData> {
  final Value<String> id;
  final Value<int> createdAt;
  final Value<String> title;
  final Value<String?> descriptionMarkdown;
  final Value<int?> dueDate;
  final Value<int> status;
  final Value<int?> completedAt;
  final Value<String?> closingNote;
  final Value<int> rowid;
  const TasksCompanion({
    this.id = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.title = const Value.absent(),
    this.descriptionMarkdown = const Value.absent(),
    this.dueDate = const Value.absent(),
    this.status = const Value.absent(),
    this.completedAt = const Value.absent(),
    this.closingNote = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TasksCompanion.insert({
    required String id,
    this.createdAt = const Value.absent(),
    required String title,
    this.descriptionMarkdown = const Value.absent(),
    this.dueDate = const Value.absent(),
    required int status,
    this.completedAt = const Value.absent(),
    this.closingNote = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       title = Value(title),
       status = Value(status);
  static Insertable<TasksData> custom({
    Expression<String>? id,
    Expression<int>? createdAt,
    Expression<String>? title,
    Expression<String>? descriptionMarkdown,
    Expression<int>? dueDate,
    Expression<int>? status,
    Expression<int>? completedAt,
    Expression<String>? closingNote,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (createdAt != null) 'created_at': createdAt,
      if (title != null) 'title': title,
      if (descriptionMarkdown != null)
        'description_markdown': descriptionMarkdown,
      if (dueDate != null) 'due_date': dueDate,
      if (status != null) 'status': status,
      if (completedAt != null) 'completed_at': completedAt,
      if (closingNote != null) 'closing_note': closingNote,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TasksCompanion copyWith({
    Value<String>? id,
    Value<int>? createdAt,
    Value<String>? title,
    Value<String?>? descriptionMarkdown,
    Value<int?>? dueDate,
    Value<int>? status,
    Value<int?>? completedAt,
    Value<String?>? closingNote,
    Value<int>? rowid,
  }) {
    return TasksCompanion(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      title: title ?? this.title,
      descriptionMarkdown: descriptionMarkdown ?? this.descriptionMarkdown,
      dueDate: dueDate ?? this.dueDate,
      status: status ?? this.status,
      completedAt: completedAt ?? this.completedAt,
      closingNote: closingNote ?? this.closingNote,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (descriptionMarkdown.present) {
      map['description_markdown'] = Variable<String>(descriptionMarkdown.value);
    }
    if (dueDate.present) {
      map['due_date'] = Variable<int>(dueDate.value);
    }
    if (status.present) {
      map['status'] = Variable<int>(status.value);
    }
    if (completedAt.present) {
      map['completed_at'] = Variable<int>(completedAt.value);
    }
    if (closingNote.present) {
      map['closing_note'] = Variable<String>(closingNote.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TasksCompanion(')
          ..write('id: $id, ')
          ..write('createdAt: $createdAt, ')
          ..write('title: $title, ')
          ..write('descriptionMarkdown: $descriptionMarkdown, ')
          ..write('dueDate: $dueDate, ')
          ..write('status: $status, ')
          ..write('completedAt: $completedAt, ')
          ..write('closingNote: $closingNote, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class Tags extends Table with TableInfo<Tags, TagsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Tags(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL UNIQUE',
  );
  @override
  List<GeneratedColumn> get $columns => [id, name];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'tags';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TagsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TagsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
    );
  }

  @override
  Tags createAlias(String alias) {
    return Tags(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TagsData extends DataClass implements Insertable<TagsData> {
  final String id;
  final String name;
  const TagsData({required this.id, required this.name});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    return map;
  }

  TagsCompanion toCompanion(bool nullToAbsent) {
    return TagsCompanion(id: Value(id), name: Value(name));
  }

  factory TagsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TagsData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
    };
  }

  TagsData copyWith({String? id, String? name}) =>
      TagsData(id: id ?? this.id, name: name ?? this.name);
  TagsData copyWithCompanion(TagsCompanion data) {
    return TagsData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TagsData(')
          ..write('id: $id, ')
          ..write('name: $name')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, name);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TagsData && other.id == this.id && other.name == this.name);
}

class TagsCompanion extends UpdateCompanion<TagsData> {
  final Value<String> id;
  final Value<String> name;
  final Value<int> rowid;
  const TagsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TagsCompanion.insert({
    required String id,
    required String name,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name);
  static Insertable<TagsData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TagsCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<int>? rowid,
  }) {
    return TagsCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TagsCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class MoodEntryTags extends Table
    with TableInfo<MoodEntryTags, MoodEntryTagsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MoodEntryTags(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> moodEntryId = GeneratedColumn<String>(
    'mood_entry_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES mood_entries(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> tagId = GeneratedColumn<String>(
    'tag_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES tags(id)ON DELETE CASCADE',
  );
  @override
  List<GeneratedColumn> get $columns => [moodEntryId, tagId];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'mood_entry_tags';
  @override
  Set<GeneratedColumn> get $primaryKey => {moodEntryId, tagId};
  @override
  MoodEntryTagsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return MoodEntryTagsData(
      moodEntryId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}mood_entry_id'],
      )!,
      tagId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}tag_id'],
      )!,
    );
  }

  @override
  MoodEntryTags createAlias(String alias) {
    return MoodEntryTags(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(mood_entry_id, tag_id)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class MoodEntryTagsData extends DataClass
    implements Insertable<MoodEntryTagsData> {
  final String moodEntryId;
  final String tagId;
  const MoodEntryTagsData({required this.moodEntryId, required this.tagId});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['mood_entry_id'] = Variable<String>(moodEntryId);
    map['tag_id'] = Variable<String>(tagId);
    return map;
  }

  MoodEntryTagsCompanion toCompanion(bool nullToAbsent) {
    return MoodEntryTagsCompanion(
      moodEntryId: Value(moodEntryId),
      tagId: Value(tagId),
    );
  }

  factory MoodEntryTagsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return MoodEntryTagsData(
      moodEntryId: serializer.fromJson<String>(json['moodEntryId']),
      tagId: serializer.fromJson<String>(json['tagId']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'moodEntryId': serializer.toJson<String>(moodEntryId),
      'tagId': serializer.toJson<String>(tagId),
    };
  }

  MoodEntryTagsData copyWith({String? moodEntryId, String? tagId}) =>
      MoodEntryTagsData(
        moodEntryId: moodEntryId ?? this.moodEntryId,
        tagId: tagId ?? this.tagId,
      );
  MoodEntryTagsData copyWithCompanion(MoodEntryTagsCompanion data) {
    return MoodEntryTagsData(
      moodEntryId: data.moodEntryId.present
          ? data.moodEntryId.value
          : this.moodEntryId,
      tagId: data.tagId.present ? data.tagId.value : this.tagId,
    );
  }

  @override
  String toString() {
    return (StringBuffer('MoodEntryTagsData(')
          ..write('moodEntryId: $moodEntryId, ')
          ..write('tagId: $tagId')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(moodEntryId, tagId);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is MoodEntryTagsData &&
          other.moodEntryId == this.moodEntryId &&
          other.tagId == this.tagId);
}

class MoodEntryTagsCompanion extends UpdateCompanion<MoodEntryTagsData> {
  final Value<String> moodEntryId;
  final Value<String> tagId;
  final Value<int> rowid;
  const MoodEntryTagsCompanion({
    this.moodEntryId = const Value.absent(),
    this.tagId = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  MoodEntryTagsCompanion.insert({
    required String moodEntryId,
    required String tagId,
    this.rowid = const Value.absent(),
  }) : moodEntryId = Value(moodEntryId),
       tagId = Value(tagId);
  static Insertable<MoodEntryTagsData> custom({
    Expression<String>? moodEntryId,
    Expression<String>? tagId,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (moodEntryId != null) 'mood_entry_id': moodEntryId,
      if (tagId != null) 'tag_id': tagId,
      if (rowid != null) 'rowid': rowid,
    });
  }

  MoodEntryTagsCompanion copyWith({
    Value<String>? moodEntryId,
    Value<String>? tagId,
    Value<int>? rowid,
  }) {
    return MoodEntryTagsCompanion(
      moodEntryId: moodEntryId ?? this.moodEntryId,
      tagId: tagId ?? this.tagId,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (moodEntryId.present) {
      map['mood_entry_id'] = Variable<String>(moodEntryId.value);
    }
    if (tagId.present) {
      map['tag_id'] = Variable<String>(tagId.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('MoodEntryTagsCompanion(')
          ..write('moodEntryId: $moodEntryId, ')
          ..write('tagId: $tagId, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class JournalEntryTags extends Table
    with TableInfo<JournalEntryTags, JournalEntryTagsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  JournalEntryTags(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> journalEntryId = GeneratedColumn<String>(
    'journal_entry_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES journal_entries(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> tagId = GeneratedColumn<String>(
    'tag_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES tags(id)ON DELETE CASCADE',
  );
  @override
  List<GeneratedColumn> get $columns => [journalEntryId, tagId];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'journal_entry_tags';
  @override
  Set<GeneratedColumn> get $primaryKey => {journalEntryId, tagId};
  @override
  JournalEntryTagsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return JournalEntryTagsData(
      journalEntryId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}journal_entry_id'],
      )!,
      tagId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}tag_id'],
      )!,
    );
  }

  @override
  JournalEntryTags createAlias(String alias) {
    return JournalEntryTags(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(journal_entry_id, tag_id)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class JournalEntryTagsData extends DataClass
    implements Insertable<JournalEntryTagsData> {
  final String journalEntryId;
  final String tagId;
  const JournalEntryTagsData({
    required this.journalEntryId,
    required this.tagId,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['journal_entry_id'] = Variable<String>(journalEntryId);
    map['tag_id'] = Variable<String>(tagId);
    return map;
  }

  JournalEntryTagsCompanion toCompanion(bool nullToAbsent) {
    return JournalEntryTagsCompanion(
      journalEntryId: Value(journalEntryId),
      tagId: Value(tagId),
    );
  }

  factory JournalEntryTagsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return JournalEntryTagsData(
      journalEntryId: serializer.fromJson<String>(json['journalEntryId']),
      tagId: serializer.fromJson<String>(json['tagId']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'journalEntryId': serializer.toJson<String>(journalEntryId),
      'tagId': serializer.toJson<String>(tagId),
    };
  }

  JournalEntryTagsData copyWith({String? journalEntryId, String? tagId}) =>
      JournalEntryTagsData(
        journalEntryId: journalEntryId ?? this.journalEntryId,
        tagId: tagId ?? this.tagId,
      );
  JournalEntryTagsData copyWithCompanion(JournalEntryTagsCompanion data) {
    return JournalEntryTagsData(
      journalEntryId: data.journalEntryId.present
          ? data.journalEntryId.value
          : this.journalEntryId,
      tagId: data.tagId.present ? data.tagId.value : this.tagId,
    );
  }

  @override
  String toString() {
    return (StringBuffer('JournalEntryTagsData(')
          ..write('journalEntryId: $journalEntryId, ')
          ..write('tagId: $tagId')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(journalEntryId, tagId);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is JournalEntryTagsData &&
          other.journalEntryId == this.journalEntryId &&
          other.tagId == this.tagId);
}

class JournalEntryTagsCompanion extends UpdateCompanion<JournalEntryTagsData> {
  final Value<String> journalEntryId;
  final Value<String> tagId;
  final Value<int> rowid;
  const JournalEntryTagsCompanion({
    this.journalEntryId = const Value.absent(),
    this.tagId = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  JournalEntryTagsCompanion.insert({
    required String journalEntryId,
    required String tagId,
    this.rowid = const Value.absent(),
  }) : journalEntryId = Value(journalEntryId),
       tagId = Value(tagId);
  static Insertable<JournalEntryTagsData> custom({
    Expression<String>? journalEntryId,
    Expression<String>? tagId,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (journalEntryId != null) 'journal_entry_id': journalEntryId,
      if (tagId != null) 'tag_id': tagId,
      if (rowid != null) 'rowid': rowid,
    });
  }

  JournalEntryTagsCompanion copyWith({
    Value<String>? journalEntryId,
    Value<String>? tagId,
    Value<int>? rowid,
  }) {
    return JournalEntryTagsCompanion(
      journalEntryId: journalEntryId ?? this.journalEntryId,
      tagId: tagId ?? this.tagId,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (journalEntryId.present) {
      map['journal_entry_id'] = Variable<String>(journalEntryId.value);
    }
    if (tagId.present) {
      map['tag_id'] = Variable<String>(tagId.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('JournalEntryTagsCompanion(')
          ..write('journalEntryId: $journalEntryId, ')
          ..write('tagId: $tagId, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class AppSettings extends Table with TableInfo<AppSettings, AppSettingsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  AppSettings(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> key = GeneratedColumn<String>(
    'key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
    'value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [key, value];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'app_settings';
  @override
  Set<GeneratedColumn> get $primaryKey => {key};
  @override
  AppSettingsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return AppSettingsData(
      key: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}key'],
      )!,
      value: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}value'],
      )!,
    );
  }

  @override
  AppSettings createAlias(String alias) {
    return AppSettings(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY("key")'];
  @override
  bool get dontWriteConstraints => true;
}

class AppSettingsData extends DataClass implements Insertable<AppSettingsData> {
  final String key;
  final String value;
  const AppSettingsData({required this.key, required this.value});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['key'] = Variable<String>(key);
    map['value'] = Variable<String>(value);
    return map;
  }

  AppSettingsCompanion toCompanion(bool nullToAbsent) {
    return AppSettingsCompanion(key: Value(key), value: Value(value));
  }

  factory AppSettingsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return AppSettingsData(
      key: serializer.fromJson<String>(json['key']),
      value: serializer.fromJson<String>(json['value']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'key': serializer.toJson<String>(key),
      'value': serializer.toJson<String>(value),
    };
  }

  AppSettingsData copyWith({String? key, String? value}) =>
      AppSettingsData(key: key ?? this.key, value: value ?? this.value);
  AppSettingsData copyWithCompanion(AppSettingsCompanion data) {
    return AppSettingsData(
      key: data.key.present ? data.key.value : this.key,
      value: data.value.present ? data.value.value : this.value,
    );
  }

  @override
  String toString() {
    return (StringBuffer('AppSettingsData(')
          ..write('key: $key, ')
          ..write('value: $value')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(key, value);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is AppSettingsData &&
          other.key == this.key &&
          other.value == this.value);
}

class AppSettingsCompanion extends UpdateCompanion<AppSettingsData> {
  final Value<String> key;
  final Value<String> value;
  final Value<int> rowid;
  const AppSettingsCompanion({
    this.key = const Value.absent(),
    this.value = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  AppSettingsCompanion.insert({
    required String key,
    required String value,
    this.rowid = const Value.absent(),
  }) : key = Value(key),
       value = Value(value);
  static Insertable<AppSettingsData> custom({
    Expression<String>? key,
    Expression<String>? value,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (key != null) 'key': key,
      if (value != null) 'value': value,
      if (rowid != null) 'rowid': rowid,
    });
  }

  AppSettingsCompanion copyWith({
    Value<String>? key,
    Value<String>? value,
    Value<int>? rowid,
  }) {
    return AppSettingsCompanion(
      key: key ?? this.key,
      value: value ?? this.value,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (key.present) {
      map['key'] = Variable<String>(key.value);
    }
    if (value.present) {
      map['value'] = Variable<String>(value.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('AppSettingsCompanion(')
          ..write('key: $key, ')
          ..write('value: $value, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class Sessions extends Table with TableInfo<Sessions, SessionsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Sessions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> scheduledFor = GeneratedColumn<int>(
    'scheduled_for',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  late final GeneratedColumn<String> agendaMarkdown = GeneratedColumn<String>(
    'agenda_markdown',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> notesMarkdown = GeneratedColumn<String>(
    'notes_markdown',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> takeawaysMarkdown =
      GeneratedColumn<String>(
        'takeaways_markdown',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    scheduledFor,
    createdAt,
    agendaMarkdown,
    notesMarkdown,
    takeawaysMarkdown,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'sessions';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  SessionsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return SessionsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      scheduledFor: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}scheduled_for'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      agendaMarkdown: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}agenda_markdown'],
      ),
      notesMarkdown: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes_markdown'],
      ),
      takeawaysMarkdown: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}takeaways_markdown'],
      ),
    );
  }

  @override
  Sessions createAlias(String alias) {
    return Sessions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class SessionsData extends DataClass implements Insertable<SessionsData> {
  final String id;
  final int scheduledFor;
  final int createdAt;
  final String? agendaMarkdown;
  final String? notesMarkdown;
  final String? takeawaysMarkdown;
  const SessionsData({
    required this.id,
    required this.scheduledFor,
    required this.createdAt,
    this.agendaMarkdown,
    this.notesMarkdown,
    this.takeawaysMarkdown,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['scheduled_for'] = Variable<int>(scheduledFor);
    map['created_at'] = Variable<int>(createdAt);
    if (!nullToAbsent || agendaMarkdown != null) {
      map['agenda_markdown'] = Variable<String>(agendaMarkdown);
    }
    if (!nullToAbsent || notesMarkdown != null) {
      map['notes_markdown'] = Variable<String>(notesMarkdown);
    }
    if (!nullToAbsent || takeawaysMarkdown != null) {
      map['takeaways_markdown'] = Variable<String>(takeawaysMarkdown);
    }
    return map;
  }

  SessionsCompanion toCompanion(bool nullToAbsent) {
    return SessionsCompanion(
      id: Value(id),
      scheduledFor: Value(scheduledFor),
      createdAt: Value(createdAt),
      agendaMarkdown: agendaMarkdown == null && nullToAbsent
          ? const Value.absent()
          : Value(agendaMarkdown),
      notesMarkdown: notesMarkdown == null && nullToAbsent
          ? const Value.absent()
          : Value(notesMarkdown),
      takeawaysMarkdown: takeawaysMarkdown == null && nullToAbsent
          ? const Value.absent()
          : Value(takeawaysMarkdown),
    );
  }

  factory SessionsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return SessionsData(
      id: serializer.fromJson<String>(json['id']),
      scheduledFor: serializer.fromJson<int>(json['scheduledFor']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      agendaMarkdown: serializer.fromJson<String?>(json['agendaMarkdown']),
      notesMarkdown: serializer.fromJson<String?>(json['notesMarkdown']),
      takeawaysMarkdown: serializer.fromJson<String?>(
        json['takeawaysMarkdown'],
      ),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'scheduledFor': serializer.toJson<int>(scheduledFor),
      'createdAt': serializer.toJson<int>(createdAt),
      'agendaMarkdown': serializer.toJson<String?>(agendaMarkdown),
      'notesMarkdown': serializer.toJson<String?>(notesMarkdown),
      'takeawaysMarkdown': serializer.toJson<String?>(takeawaysMarkdown),
    };
  }

  SessionsData copyWith({
    String? id,
    int? scheduledFor,
    int? createdAt,
    Value<String?> agendaMarkdown = const Value.absent(),
    Value<String?> notesMarkdown = const Value.absent(),
    Value<String?> takeawaysMarkdown = const Value.absent(),
  }) => SessionsData(
    id: id ?? this.id,
    scheduledFor: scheduledFor ?? this.scheduledFor,
    createdAt: createdAt ?? this.createdAt,
    agendaMarkdown: agendaMarkdown.present
        ? agendaMarkdown.value
        : this.agendaMarkdown,
    notesMarkdown: notesMarkdown.present
        ? notesMarkdown.value
        : this.notesMarkdown,
    takeawaysMarkdown: takeawaysMarkdown.present
        ? takeawaysMarkdown.value
        : this.takeawaysMarkdown,
  );
  SessionsData copyWithCompanion(SessionsCompanion data) {
    return SessionsData(
      id: data.id.present ? data.id.value : this.id,
      scheduledFor: data.scheduledFor.present
          ? data.scheduledFor.value
          : this.scheduledFor,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      agendaMarkdown: data.agendaMarkdown.present
          ? data.agendaMarkdown.value
          : this.agendaMarkdown,
      notesMarkdown: data.notesMarkdown.present
          ? data.notesMarkdown.value
          : this.notesMarkdown,
      takeawaysMarkdown: data.takeawaysMarkdown.present
          ? data.takeawaysMarkdown.value
          : this.takeawaysMarkdown,
    );
  }

  @override
  String toString() {
    return (StringBuffer('SessionsData(')
          ..write('id: $id, ')
          ..write('scheduledFor: $scheduledFor, ')
          ..write('createdAt: $createdAt, ')
          ..write('agendaMarkdown: $agendaMarkdown, ')
          ..write('notesMarkdown: $notesMarkdown, ')
          ..write('takeawaysMarkdown: $takeawaysMarkdown')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    scheduledFor,
    createdAt,
    agendaMarkdown,
    notesMarkdown,
    takeawaysMarkdown,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is SessionsData &&
          other.id == this.id &&
          other.scheduledFor == this.scheduledFor &&
          other.createdAt == this.createdAt &&
          other.agendaMarkdown == this.agendaMarkdown &&
          other.notesMarkdown == this.notesMarkdown &&
          other.takeawaysMarkdown == this.takeawaysMarkdown);
}

class SessionsCompanion extends UpdateCompanion<SessionsData> {
  final Value<String> id;
  final Value<int> scheduledFor;
  final Value<int> createdAt;
  final Value<String?> agendaMarkdown;
  final Value<String?> notesMarkdown;
  final Value<String?> takeawaysMarkdown;
  final Value<int> rowid;
  const SessionsCompanion({
    this.id = const Value.absent(),
    this.scheduledFor = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.agendaMarkdown = const Value.absent(),
    this.notesMarkdown = const Value.absent(),
    this.takeawaysMarkdown = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  SessionsCompanion.insert({
    required String id,
    required int scheduledFor,
    this.createdAt = const Value.absent(),
    this.agendaMarkdown = const Value.absent(),
    this.notesMarkdown = const Value.absent(),
    this.takeawaysMarkdown = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       scheduledFor = Value(scheduledFor);
  static Insertable<SessionsData> custom({
    Expression<String>? id,
    Expression<int>? scheduledFor,
    Expression<int>? createdAt,
    Expression<String>? agendaMarkdown,
    Expression<String>? notesMarkdown,
    Expression<String>? takeawaysMarkdown,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (scheduledFor != null) 'scheduled_for': scheduledFor,
      if (createdAt != null) 'created_at': createdAt,
      if (agendaMarkdown != null) 'agenda_markdown': agendaMarkdown,
      if (notesMarkdown != null) 'notes_markdown': notesMarkdown,
      if (takeawaysMarkdown != null) 'takeaways_markdown': takeawaysMarkdown,
      if (rowid != null) 'rowid': rowid,
    });
  }

  SessionsCompanion copyWith({
    Value<String>? id,
    Value<int>? scheduledFor,
    Value<int>? createdAt,
    Value<String?>? agendaMarkdown,
    Value<String?>? notesMarkdown,
    Value<String?>? takeawaysMarkdown,
    Value<int>? rowid,
  }) {
    return SessionsCompanion(
      id: id ?? this.id,
      scheduledFor: scheduledFor ?? this.scheduledFor,
      createdAt: createdAt ?? this.createdAt,
      agendaMarkdown: agendaMarkdown ?? this.agendaMarkdown,
      notesMarkdown: notesMarkdown ?? this.notesMarkdown,
      takeawaysMarkdown: takeawaysMarkdown ?? this.takeawaysMarkdown,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (scheduledFor.present) {
      map['scheduled_for'] = Variable<int>(scheduledFor.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (agendaMarkdown.present) {
      map['agenda_markdown'] = Variable<String>(agendaMarkdown.value);
    }
    if (notesMarkdown.present) {
      map['notes_markdown'] = Variable<String>(notesMarkdown.value);
    }
    if (takeawaysMarkdown.present) {
      map['takeaways_markdown'] = Variable<String>(takeawaysMarkdown.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('SessionsCompanion(')
          ..write('id: $id, ')
          ..write('scheduledFor: $scheduledFor, ')
          ..write('createdAt: $createdAt, ')
          ..write('agendaMarkdown: $agendaMarkdown, ')
          ..write('notesMarkdown: $notesMarkdown, ')
          ..write('takeawaysMarkdown: $takeawaysMarkdown, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV3 extends GeneratedDatabase {
  DatabaseAtV3(QueryExecutor e) : super(e);
  late final MoodEntries moodEntries = MoodEntries(this);
  late final MoodEntryEmotions moodEntryEmotions = MoodEntryEmotions(this);
  late final JournalEntries journalEntries = JournalEntries(this);
  late final Tasks tasks = Tasks(this);
  late final Tags tags = Tags(this);
  late final MoodEntryTags moodEntryTags = MoodEntryTags(this);
  late final JournalEntryTags journalEntryTags = JournalEntryTags(this);
  late final AppSettings appSettings = AppSettings(this);
  late final Sessions sessions = Sessions(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    moodEntries,
    moodEntryEmotions,
    journalEntries,
    tasks,
    tags,
    moodEntryTags,
    journalEntryTags,
    appSettings,
    sessions,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'mood_entries',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('mood_entry_emotions', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'mood_entries',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('mood_entry_tags', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'tags',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('mood_entry_tags', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'journal_entries',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('journal_entry_tags', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'tags',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('journal_entry_tags', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 3;
}
